elCicdDefs:
  CONFIGMAP: configmap
  CPU_UTILIZATION: 90
  REPLICAS: 1
  MAX_REPLICAS: 3
  PORT: 8080
  CGROUP: cgroup
  
elCicdDefs-dev:
  CPU_UTILIZATION: 50
  PORT: 8081

elCicdDefs-qa:
  MAX_REPLICAS: 4
  REPLICAS: 3
  
elCicdDefs-stg:
  CPU_UTILIZATION: 50

elCicdDefs-prod:
  MAX_REPLICAS: 5

elCicdTemplates:
- templateName: deployment|service
  replicas: $<REPLICAS>
  port: $<PORT>
  env:
  - name: password
    valueFrom:
      secretKeyRef:
        key: password
        name: $<COMPONENT_NAME>-sealed-secret
  - name: topicname
    valueFrom:
      configMapKeyRef:
        key: topicname
        name: $<COMPONENT_NAME>-$<CONFIGMAP>
  - name: $<CGROUP>
    valueFrom:
      configMapKeyRef:
        key: $<CGROUP>
        name: $<COMPONENT_NAME>-$<CONFIGMAP>

- templateName: configMap
  objName: $<COMPONENT_NAME>-$<CONFIGMAP>
  data:
    $<CGROUP>: $<CGROUP>
    topicname: $<SDLC_ENV>-topic

- templateName: horizontalPodAutoscaler
  maxReplicas: $<MAX_REPLICAS>
  metrics:
  - type: resource
    name: cpu
    target:
      type: Utilization
      averageUtilization: $<CPU_UTILIZATION>